- README.org
I have had a hard time making my first push to github. Meng, could you please check if you can pull this change into the langspec branch?
> added comments to README.org (marked with Comment MS)

- README.org
Added a few more comments, essentially regarding the question of an _abstract syntax_ for L4 and a _type system_. These seem a prerequisite for starting to work on a semantics.
> added more comments to README.org

- bnfc/l4/test7.l4
two potatoes please for $20 exactly.
> let's buy two potatoes

- bnfc/src-l4/ToProlog.hs
Experimental: what happens when we choose "Rebase and merge" on GitHub
1) Rebase feature onto main (= feature branch's history is rewritten, no changes in main)
2) Merge rebased commits into main (= add the history-rewritten feature branch's commits into main)
> Potatoes and cabbages

- bnfc/Makefile
- bnfc/src-l4/ToGF.hs
- grammars/Bike.gf
- grammars/BikeEng.gf
- grammars/Gastronomy.gf
- grammars/GastronomyEng.gf
- grammars/Rule.gf
- grammars/RuleEng.gf
Some more structures.
```
RULE 4 Cabbage DEFINE Item IS cabbage WHEN Item.species ~ ["Brassica chinensis" | "Brassica oleracea"];
an item is a cabbage , when the species of the item is Brassica chinensis or Brassica oleracea
Abstract syntax tree in GF:
When (MDefTermIs Item (TDet ASg Cabbage)) (MDefTermMatch (TDet TheSg (ComplKind Species (TDet TheSg Item))) (ConjTerm Or (BaseTerm (StrTerm "Brassica chinensis") (StrTerm "Brassica oleracea"))))
```
Next plan is to add tests.
> Updates in NLG

- README.org
- bnfc/l4/generated/cabbage.l4.gold
- bnfc/l4/generated/potato.l4.gold
- bnfc/l4/test1.l4.gold
- bnfc/src-l4/ToGF.hs
- grammars/Rule.gf
- grammars/RuleEng.gf
A few new constructs in ToGF and the grammars.
Fixed the syntax of some L4 code examples to what looks nicer to me.
> Fix ToGF after changes in L4 parser + some new stuff

- bnfc/README.org
> Documentation update: Installation instructions in dsl/bnfc/README.org

- lib/haskell/natural4/grammars/BareRG.gf
- lib/haskell/natural4/grammars/BareRGEng.gf
- lib/haskell/natural4/grammars/UDApp.labels
- lib/haskell/natural4/grammars/UDAppEng.labels
- lib/haskell/natural4/grammars/UDCat.gf
- lib/haskell/natural4/grammars/tests/basic.conllu.gold
- lib/haskell/natural4/grammars/tests/succeeds.conllu.gold
- lib/haskell/natural4/src/LS/NLP/NLG.hs
- lib/haskell/natural4/src/LS/NLP/UDExt.hs
- lib/haskell/natural4/test/TestNLG.hs
More work on bsp2gf, also WIP making more use of the Haskell version of the GF abstract syntax instead of the untyped PGF.Expr everywhere
> More work on NLG

- lib/haskell/natural4/grammars/BareRGEng.gf
- lib/haskell/natural4/grammars/UDApp.gf
- lib/haskell/natural4/grammars/UDApp.labels
- lib/haskell/natural4/grammars/UDAppEng.gf
- lib/haskell/natural4/grammars/UDCat.gf
- lib/haskell/natural4/grammars/UDCatEng.gf
- lib/haskell/natural4/grammars/tests/succeeds.conllu
- lib/haskell/natural4/grammars/tests/succeeds.conllu.gold
- lib/haskell/natural4/natural4.cabal
- lib/haskell/natural4/package.yaml
- lib/haskell/natural4/src/LS/NLP/NLG.hs
- lib/haskell/natural4/src/LS/NLP/UDExt.hs
- lib/haskell/natural4/stack.yaml
- lib/haskell/natural4/stack.yaml.lock
- lib/haskell/natural4/test/TestNLG.hs
This replaces the python udpipe program with c++ udpipe bindings
This also has the advantage of automatically installing and not needing to manually download all the python deps
TODO:
- Add the model in git so you don't have to manually download it
- Remove all the old unused code relating to python bindings
Fixes #32
> Udpipe c++-bindings

- lib/haskell/natural4/app/Main.hs
- lib/haskell/natural4/natural4.cabal
- lib/haskell/natural4/package.yaml
- lib/haskell/natural4/src/LS/NLP/NLG.hs
- lib/haskell/natural4/src/LS/XPile/VueJSON.hs
- lib/haskell/natural4/test/Spec.hs
- lib/haskell/natural4/test/TestNLG.hs
This will hopefully speed things up a bit
> Run tests concurrently

- lib/haskell/natural4/app/Main.hs
- lib/haskell/natural4/natural4.cabal
- lib/haskell/natural4/package.yaml
- lib/haskell/natural4/src/LS/NLP/NLG.hs
- lib/haskell/natural4/src/LS/XPile/VueJSON.hs
- lib/haskell/natural4/test/Spec.hs
- lib/haskell/natural4/test/TestNLG.hs
> Run tests in parallel

- lib/haskell/natural4/src/LS/Error.hs
okay, this really compiles this time
> another fix to Text Lazy, not sure why this went funny the first time

- .github/workflows/haskell.yml
Update cache key to include natural4 and anyall cabal files as it looks like previously natural4 build cache is not saved
> Update cache key

- lib/haskell/natural4/app/Main.hs
todo: un-hardcode this by extracting from RPMT
> hardcode the NLDict material so the program at least typechecks

- lib/haskell/natural4/app/Main.hs
- lib/haskell/natural4/src/LS/Lib.hs
- lib/haskell/natural4/src/LS/XPile/CoreL4.hs
- lib/haskell/natural4/src/LS/XPile/NaturalLanguage.hs
- lib/haskell/natural4/src/LS/XPile/README.org
Suppose you want to add a new transpiler. This pull request contains skeletal examples of tweaks to the source files needed to do that.
> HOWTO add a new transpiler

- lib/haskell/anyall/src/AnyAll/SVGLadder.hs
- lib/haskell/natural4/src/LS/Types.hs
cosmetic changes to the anyall rendering to svg -- not sure why this fell out of the current main
> Svgladder 1

- lib/haskell/natural4/grammars/UDApp.gf
- lib/haskell/natural4/grammars/UDApp.labels
- lib/haskell/natural4/grammars/UDAppEng.gf
- lib/haskell/natural4/grammars/UDAppMay.gf
- lib/haskell/natural4/grammars/UDExt.gf
- lib/haskell/natural4/grammars/UDExtEng.gf
- lib/haskell/natural4/grammars/UDExtMay.gf
- lib/haskell/natural4/src/LS/NLP/NLG.hs
- lib/haskell/natural4/src/LS/NLP/UDExt.hs
New try without getting git sad.
- change type of HornClause2. I really don't remember why.
- replace root_xcomp_obj with root_obj_xcomp, the example sentence is "render it unlikely". Seems more plausible than "render unlikely it", so this seems to make sense.
> NLG updates from May (new try)

- lib/haskell/natural4/grammars/BareRG.gf
- lib/haskell/natural4/grammars/BareRGEng.gf
- lib/haskell/natural4/grammars/BareRGMay.gf
- lib/haskell/natural4/grammars/UDExt.gf
- lib/haskell/natural4/package.yaml
- lib/haskell/natural4/src/LS/NLP/NLG.hs
- lib/haskell/natural4/src/LS/XPile/Markdown.hs
Add grammar files as data-files in cabal
> closes #221; add grammar files as data-files in cabal

- lib/haskell/natural4/src/LS/Types.hs
succeeds immediately prior pull request
> preserve join style in bsr2text

- lib/haskell/natural4/src/LS/Interpreter.hs
- lib/haskell/natural4/src/LS/NLP/NLG.hs
I commented out some print statements so the system doesn't produce quite so much STDOUT. I hope that output wasn't essential to functionality! If it was, please comment so this PR can be reverted.
> Reduce nlg verbosity

- lib/haskell/natural4/src/LS/XPile/Maude/Rule.hs
> small bug fix

- lib/haskell/anyall/stack.yaml
- lib/haskell/anyall/stack.yaml.lock
resolves https://app.asana.com/0/1204438452722905/1204438524111938
> add a section to the script walking through the user-facing apps and transpilation targets

- lib/haskell/anyall/stack.yaml
- lib/haskell/anyall/stack.yaml.lock
- lib/haskell/explainable/stack.yaml
- lib/haskell/explainable/stack.yaml.lock
- lib/haskell/extract/stack.yaml
- lib/haskell/extract/stack.yaml.lock
- lib/haskell/natural4/stack.yaml
- lib/haskell/natural4/stack.yaml.lock
> Revert "Upgrade stack resolver to lts-20.25"

- lib/haskell/natural4/src/LS/BasicTypes.hs
- lib/haskell/natural4/src/LS/Interpreter.hs
- lib/haskell/natural4/src/LS/PrettyPrinter.hs
- lib/haskell/natural4/src/LS/RelationalPredicates.hs
- lib/haskell/natural4/src/LS/Types.hs
- lib/haskell/natural4/src/LS/XPile/README.org
- lib/haskell/natural4/src/LS/XPile/Typescript.hs
> 20230803 typescript

- lib/haskell/natural4/.ghci
- lib/haskell/natural4/src/LS/BasicTypes.hs
- lib/haskell/natural4/src/LS/DataFlow.hs
- lib/haskell/natural4/src/LS/Interpreter.hs
- lib/haskell/natural4/src/LS/PrettyPrinter.hs
- lib/haskell/natural4/src/LS/Rule.hs
- lib/haskell/natural4/src/LS/Types.hs
- lib/haskell/natural4/src/LS/XPile/Org.hs
- lib/haskell/natural4/src/LS/XPile/Typescript.hs
some typescript-specific changes – this is a subset of work done in the other branch https://github.com/smucclaw/dsl/tree/20230803-typescript
> 20230822 typescript new

- lib/haskell/anyall/src/AnyAll/BoolStruct.hs
- lib/haskell/natural4/app/Main.hs
- lib/haskell/natural4/src/LS/BasicTypes.hs
This allows us to do the kind of syntax seen in https://docs.google.com/spreadsheets/d/1leBCZhgDsn-Abg2H_OINGGv-8Gpf9mzuX1RR56v0Sss/edit?pli=1#gid=1380547553
> add syntactic sugar allowing "..." as a connector; semantically, "AND"

- lib/haskell/natural4/src/LS/BasicTypes.hs
- lib/haskell/natural4/src/LS/PrettyPrinter.hs
- lib/haskell/natural4/src/LS/RelationalPredicates.hs
- lib/haskell/natural4/src/LS/Types.hs
- lib/haskell/natural4/src/LS/XPile/Prolog.hs
This PR shows how to extend the inbuilt type keywords
> add support for Set0 (set) and Set1 (nonempty set) similar to List0 List1

- lib/haskell/natural4/src/LS/BasicTypes.hs
§ section symbol
¶ paragraph symbol
H1 through H6
> add support for alternative rulemarkers

- lib/haskell/anyall/stack.yaml
- lib/haskell/anyall/stack.yaml.lock
- lib/haskell/explainable/explainable.cabal
- lib/haskell/explainable/package.yaml
- lib/haskell/explainable/src/Explainable/MathLang.hs
- lib/haskell/explainable/src/Explainable/ToGraphViz.hs
- lib/haskell/explainable/stack.yaml
- lib/haskell/explainable/stack.yaml.lock
- lib/haskell/extract/stack.yaml
- lib/haskell/extract/stack.yaml.lock
- lib/haskell/natural4/src/LS/XPile/JSONRanges.hs
- lib/haskell/natural4/stack.yaml
- lib/haskell/natural4/stack.yaml.lock
> 20231029 mathlang

- lib/haskell/explainable/src/Explainable/MathLang.hs
- lib/haskell/natural4/app/Main.hs
- lib/haskell/natural4/src/LS/Rule.hs
- lib/haskell/natural4/src/LS/XPile/XPMathLang.hs
this does not compile, but shows examples of what is supposed to happen
> [BROKEN] more illustrative examples

- lib/haskell/natural4/src/LS/Lib.hs
Cleanup LS.Lib, mainly:
- Linting
- More string interpolation
> cleanup lib

- lib/haskell/natural4/src/LS/XPile/MathLang/GenericMathLang/ToGenericMathLang.hs
- lib/haskell/natural4/src/LS/XPile/MathLang/GenericMathLang/TranslateL4.hs
> Generic MathLang: Add more docs / comments; clean up non-exhaustive pattern matches and some redundant imports

- lib/haskell/natural4/src/LS/XPile/MathLang/MathLang.hs
- lib/haskell/natural4/test/LS/XPile/GenericMathLang/TranslateL4Spec.hs
Result of applying to MustSing5:
```typescript
export const Qualifies = () => {return new tsm.BoolFold ( "Qualifies"
, tsm.BoolFoldOp.All
, [ new tsm.GetVar ("walks")
, new tsm.BoolFold ( "any/all"
, tsm.BoolFoldOp.All
, [ new tsm.BoolFold ( "any/all"
, tsm.BoolFoldOp.Any
, [ new tsm.BoolFold ( "any/all"
, tsm.BoolFoldOp.All
, [ new tsm.BoolFold ( "any/all"
, tsm.BoolFoldOp.Any
, [ new tsm.GetVar ("alcoholic")
, new tsm.GetVar ("non-alcoholic") ] )
, new tsm.BoolFold ( "any/all"
, tsm.BoolFoldOp.All
, [ new tsm.BoolFold ( "any/all"
, tsm.BoolFoldOp.Any
, [ new tsm.GetVar ("in part")
, new tsm.GetVar ("in whole") ] ) ] ) ] )
, new tsm.GetVar ("eats") ] ) ] ) ] )}
```
> Expand variables in rule when translating into Typescript

- lib/haskell/.gitignore
- lib/haskell/natural4/test/LS/XPile/GenericMathLang/TranslateL4Spec.hs
- lib/haskell/natural4/test/testdata/golden/mustSing.expected
- lib/haskell/natural4/test/testdata/golden/pau.expected
Makes it easier to update tests, and review changes to the typescript backend.
> Prefer golden files over string blobs

- lib/haskell/natural4/src/LS/Interpreter.hs
Also removes some dead code and fixes some warnings.
> Some comments in interpreter.

- lib/haskell/natural4/app/Main.hs
- lib/haskell/natural4/src/LS/Interpreter.hs
- lib/haskell/natural4/src/LS/Types.hs
- lib/haskell/natural4/src/LS/XPile/CoreL4.hs
- lib/haskell/natural4/test/LS/XPile/GenericMathLang/TranslateL4Spec.hs
- lib/haskell/natural4/test/Parsing/BoolStructParserSpec.hs
- lib/haskell/natural4/test/Parsing/CoreL4ParserSpec.hs
InterpreterOptions were unused in the codebase.
> Remove unused InterpreterOptions

- lib/haskell/natural4/app/Main.hs
- lib/haskell/natural4/src/LS/Log.hs
- lib/haskell/natural4/src/LS/NLP/NL4Transformations.hs
- lib/haskell/natural4/src/LS/NLP/NLG.hs
- lib/haskell/natural4/src/LS/XPile/Purescript.hs
- lib/haskell/natural4/test/LS/NLGSpec.hs
Move initialisation code to NLG.hs.
Allows us to re-use the initialisation code for tests without code copying.
Move away from XPile and similar logging utilities as they allow us to easily (and accidentally) ignore errors.
Prefer the co-functor style logging introduced by `Log`. Replace explicit error handling with `ExceptT`, which is well-known.
Avoid `unsafeInterleaveIO` and prefer `once`, which avoids any kind of unsafe, or lazy IO.
> Refactor NLGEnv initialisation

- lib/haskell/hie.yaml
- lib/haskell/web-service/package.yaml
- lib/haskell/web-service/src/Application.hs
- lib/haskell/web-service/src/Backend/Api.hs
- lib/haskell/web-service/src/Backend/Explainable.hs
- lib/haskell/web-service/src/Backend/Simala.hs
- lib/haskell/web-service/src/Examples.hs
- lib/haskell/web-service/src/Schema.hs
- lib/haskell/web-service/src/Server.hs
- lib/haskell/web-service/test/SchemaSpec.hs
- lib/haskell/web-service/web-service.cabal
Add three new endpoints:
* PUT: /functions/<name> Update the function with the name <name>
* POST: /functions/<name> Create a new function with the name <name>
* DELETE: /functions/<name> Delete the function with the name <name>
Refactors the code base to avoid hard-coding example programs in the
backend folder.
> Generalise Function API to allow adding and modifying new programs
