smucclaw/dsl

bnfc/Makefile

By using stack run instead, it will automatically build the showbug executable

Make the Makefile work the first time

---

bnfc/README.org
bnfc/package.yaml
bnfc/src-l4/L4/Executable.hs

As requested by the IDE team.
The '--dot' and '--gf' flag and option respectively allow for single-format output.
At this point however, there are still a number of issues: 
1) This version of the l4 executable only supports IO with STDIN and STDOUT, so '<' and '>' will have to used to denote any file IO.
2) When following the build-process listed in README.org under 'INSTALLATION', it will fail because (1). 
3) This means that the 'showbug' executable does not work in this build.
4) The intention is to add subcommand support as listed by @mengwong in the feature request, so the flags will be changed to subcommands in a future build

Work on Issue#24 : L4 Flags for dot & english output

---

bnfc/src-l4/L4/Executable.hs

Am requesting the removal of optsGF, parseFormat, and parseGFLang as they are no longer used by the CLI argument parser.

Removal of functions that are no longer in use from l4/Executable.hs

---

lib/haskell/natural4/app/Main.hs
lib/haskell/natural4/src/LS/BasicTypes.hs
lib/haskell/natural4/src/LS/Error.hs
lib/haskell/natural4/src/LS/Lib.hs
lib/haskell/natural4/src/LS/NLP/NLG.hs
lib/haskell/natural4/src/LS/NLP/WordNet.hs
lib/haskell/natural4/src/LS/ParamText.hs
lib/haskell/natural4/src/LS/Parser.hs
lib/haskell/natural4/src/LS/RelationalPredicates.hs
lib/haskell/natural4/src/LS/Tokens.hs
lib/haskell/natural4/src/LS/Types.hs
lib/haskell/natural4/src/LS/XPile/CoreL4.hs
lib/haskell/natural4/src/LS/XPile/Petri.hs
lib/haskell/natural4/src/LS/XPile/Prolog.hs
lib/haskell/natural4/src/LS/XPile/SVG.hs
lib/haskell/natural4/src/LS/XPile/Uppaal.hs
lib/haskell/natural4/src/LS/XPile/VueJSON.hs
lib/haskell/natural4/test/Spec.hs
lib/haskell/natural4/test/TestNLG.hs

some third-party libraries like the SVG drawer and text-pretty-simple
prefer Lazy so we use toStrict / fromStrict to maintain compatibility
This follows on commit 2a33528
And is probably needed before #45 can succeed

mostly deprecate Data.Text.Lazy in favour of Data.Text

---

lib/haskell/anyall/src/AnyAll/BoolStruct.hs
lib/haskell/natural4/src/LS/RelationalPredicates.hs

aaFilter has unintuitive functionality (potentially specific to use-case). Moving it to the place of usage to prevent unexpected usage.

Move aaFilter to the place of usage.

---

.github/workflows/haskell.yml

These will be intel-based mac jobs --- it's not currently possible to also get it running on apple silicon unless we host the runner ourselves.

add (intel-based) mac os 11 and 12 as build targets

---

lib/haskell/natural4/src/LS/NLP/NLG.hs
lib/haskell/natural4/src/LS/NLP/TreeTransformations.hs
lib/haskell/natural4/src/LS/XPile/VueJSON.hs
lib/haskell/natural4/test/TestNLG.hs

The original NLG.hs is split into roughly two: NLG and a new module called TreeTransformations. 
My logic for the split was as follows: I wanted to be able to only import the start category from `UDExt` in NLG. (I didn't quite succeed, as you can see that I'm also importing UDFragment, but close enough.) That way, the functions in NLG will only interact with the implementation details of the GF grammar via the start category, and all internal tree manipulation happens in TreeTransformations.
This is just a first, rather mechanical, step in the goal of swapping out the UD-based grammar to a new one. I also tried to group the functions in some reasonable way in the two modules. For instance, in TreeTransformations, lines 564-763, we can see a lot of redundancy: several functions take as an …

NLG refactor

---

lib/haskell/anyall/stack.yaml
lib/haskell/explainable/stack.yaml
lib/haskell/extract/stack.yaml
lib/haskell/natural4/stack.yaml
lib/haskell/natural4/stack.yaml.lock

lts-20.12 was the last stack resolver version on ghc-9.2.6. The latest LTS, lts-20.17, uses ghc-9.2.7 and as of hls-1.10.0, the Haskell language server supports this new ghc version. Hence we are updating the stack resolver accordingly.

Upgrade stack resolver from lts-20.12 to lts-20.17

---

lib/haskell/natural4/src/LS/XPile/ToEpilog_fm_nat.hs

The reason one might see this message even after enabling --toasp "To exclude the ToASP transpiler from a --workdir run, run natural4-exe with the --toasp option." is because the implementation of ruleToASPRule in ToASP.hs was duplicated in ToEpilog_fm_nat.hs, with no change to its error messages.
This misleading error message has since been rectified: "To exclude the ToEpilog transpiler from a --workdir run, run natural4-exe with the --toepilog option."

Fix misleading error reports about toasp 

---

lib/haskell/natural4/src/LS/XPile/Logging.hs
lib/haskell/natural4/test/LS/NLGSpec.hs
lib/haskell/natural4/test/LS/XPile/CoreL4/LogicProgramSpec.hs
lib/haskell/natural4/test/Parsing/CoreL4ParserSpec.hs

This fixes compilation for the `NLG` and `CoreL4` test cases. These failed to compile as the return types of some of the functions were changed to XPileLog and XPileLogE .

Fix to asp errors

---

lib/haskell/natural4/src/LS/XPile/Purescript.hs

This fixes compilation of the generated purescript output, and introduces string interpolation to make all the `str0 <> str1 <> str2 <> ...` stuff more readable.
Previously, syntactically incorrect output was generated in some cases, like when the NLG output is empty. For instance, the transpiler would at times output:
```
nl4eng :: Object.Object (Item String)
nl4eng = Object.fromFoldable
[]
nl4engMarking :: Marking
nl4engMarking = Marking $ Map.fromFoldable
[]
```
which is syntactically invalid because Purescript as with Haskell and Python is whitespace sensitive, so that the empty list `[]` needs to be indented by one level.
This has now been fixed.

Purs bugfix

---

.github/workflows/haskell.yml
lib/haskell/natural4/package.yaml
lib/haskell/natural4/src/LS/Rule.hs
lib/haskell/natural4/src/LS/Utils.hs
lib/haskell/natural4/src/LS/XPile/LogicalEnglish/GenLEHCs.hs
lib/haskell/natural4/src/LS/XPile/LogicalEnglish/GenNLAs.hs
lib/haskell/natural4/src/LS/XPile/LogicalEnglish/IdVars.hs
lib/haskell/natural4/src/LS/XPile/LogicalEnglish/LogicalEnglish.hs
lib/haskell/natural4/src/LS/XPile/LogicalEnglish/Pretty.hs
lib/haskell/natural4/src/LS/XPile/LogicalEnglish/README.md
lib/haskell/natural4/src/LS/XPile/LogicalEnglish/SimplifyL4.hs
lib/haskell/natural4/src/LS/XPile/LogicalEnglish/Types.hs
lib/haskell/natural4/src/LS/XPile/LogicalEnglish/Utils.hs
lib/haskell/natural4/src/LS/XPile/LogicalEnglish/ValidateL4Input.hs

This PR fixes some of the bugs in the transpiler and adds more functionality. In a nutshell, most of the functionality required by the current encoding should be there, though there's still work to be done on testing, making the design more modular, improving error diagnostics, etc.
In particular, this PR
* implements support for the ditto syntax in the transpiler
* improves handling of RPrels in SimplifyL4.hs
* adds more graceful error handling in SimplifyL4.hs
* adds some notes on LE syntax in README.md
* implements replacement of '%', '.', ','. These are currently hard-coded; in the future we can read in a .tsv with the desired replacements, a .tsv that can then be kept in sync with the web app side (since that also needs to be able to run the replacements in the other direction).
* …

More transpiler functionality and fixes from Sprint 2 (started Aug 29)

---

lib/haskell/natural4/src/LS/XPile/LogicalEnglish/Pretty.hs

LE Pretty.hs: Put comma at the end of the last non-lib template, instead of dot, since it is followed by lib templates. This should also fix the current bug in the edge case where there are 0 kept nlats

Small LE transpiler fix

---

lib/haskell/natural4/src/LS/XPile/ExportTypes.hs

- Use `Text` internally instead of `String`
- `OverloadedStrings`
- Better regex replacement via `pcre-heavy` for replacing multiple whitespaces with a single underscore `_`
- Change `Set` to `HashMap`

Quick cleanup of ExportTypes.hs

---

lib/haskell/natural4/src/LS/XPile/ExportTypes.hs

add FTInteger to parse Int date to integer type in json, it was coming out as a ref

add parsing of integer type for json, for number and int date on l4

---

lib/haskell/natural4/src/LS/XPile/LogicalEnglish/GenNLAs.hs
lib/haskell/natural4/src/LS/XPile/LogicalEnglish/IdVars.hs
lib/haskell/natural4/src/LS/XPile/LogicalEnglish/IdVars/IdVars.hs
lib/haskell/natural4/src/LS/XPile/LogicalEnglish/LogicalEnglish.hs
lib/haskell/natural4/src/LS/XPile/LogicalEnglish/ReplaceTxt.hs
lib/haskell/natural4/src/LS/XPile/LogicalEnglish/SimplifyL4.hs
lib/haskell/natural4/test/Testcases/LogicalEnglish/remove-alpha-equiv-nlas/actual.le
lib/haskell/natural4/test/Testcases/LogicalEnglish/remove-alpha-equiv-nlas/config.yml
lib/haskell/natural4/test/Testcases/LogicalEnglish/remove-alpha-equiv-nlas/expected.le
lib/haskell/natural4/test/Testcases/LogicalEnglish/remove-alpha-equiv-nlas/remove-alpha-equiv-nlas.csv

This fixes the L4 -> LE transpiler in the following ways:
- Shift regex replacement of txt upstream to `textifyMTE` so that it operates in all cells when translating from the L4 Rule types into the internal AST, rather than just on `VCell`.
- Transform floats representing `+Infinity` / `-Infinity` in `float2Text` into LE/Prolog's `inf` / `-inf`.
- Fix checking and removal of alpha equivalent natural language annotations.
- The previous implementation used a faulty regex that removed annotations like `*a person* satisfies clause 14.1.1` when there was also an annotation like `*a person* satisfies clause 14.1` that was being generated.
- A new testcase `remove-alpha-equiv-nlas` has been added to test this.

2023-10-11 le fixes

---

lib/haskell/natural4/src/LS/XPile/ExportTypes.hs
lib/haskell/natural4/test/LS/XPile/JSONSchemaSpec.hs

Previously, bug:
```json
{"$schema":"http://json-schema.org/draft-07/schema#",
"type": "object",
"properties":{"toplevel":{"$ref": "#/$defs/Person"}},
"$defs":
{"Person": {"type": "object","properties": {"name": {"type": "string"},
"dob": {"type": "string","format": "date"},
"hobbies": {"type": "array","items": {"$ref": "#/$defs/String"}},
"addresses": {"type": "array","items": {"$ref": "#/$defs/Address"}}}},
…}
```
Bug is that the type of `hobbies` was `"$ref": "#/$defs/String"`, but it should be a primitive `string`. After the fix:
```
"hobbies": {"type": "array","items": {"type": "string"}},
"addresses": {"type": "array","items": {"$ref": "#/$defs/Address"}}}},
```
So strings are now primitive, custom types still references.
Added tests, the ones for prettyprinting are in preparation …

Fix lists of primitive types in JSONSchema transpiler

---

lib/haskell/explainable/src/Explainable/MathLang.hs
lib/haskell/explainable/test/LibSpec.hs

Three things:
1. The module TaxDSL was removed, I added relevant bits of code from there straight into LibSpec. 
2. Added a nicer show function, because standard `show` didn't match the manual examples
3. Disabled one test that had a legitimate difference in result. (I don't know why, and I don't know if that test is still relevant or if the whole system is deprecated.)

Update/disable tests in Explainable to get CI working again

---

lib/haskell/natural4/src/LS/BasicTypes.hs
lib/haskell/natural4/src/LS/Interpreter.hs
lib/haskell/natural4/src/LS/XPile/Maude/Regulative/TempConstr.hs

This cleanup primarily involves using [PCRE](https://hackage.haskell.org/package/pcre-heavy) in conjunction with `ViewPatterns` to simplify and improve the efficiency of pattern matching on string types.

Some cleanup

---

lib/haskell/natural4/natural4.cabal
lib/haskell/natural4/src/LS/XPile/LogicalEnglish/IdVars.hs
lib/haskell/natural4/src/LS/XPile/MathLang/GenericMathLang/ArithOps.hs
lib/haskell/natural4/src/LS/XPile/MathLang/GenericMathLang/GenericMathLangAST.hs
lib/haskell/natural4/src/LS/XPile/MathLang/GenericMathLang/ToGenericMathLang.hs
lib/haskell/natural4/src/LS/XPile/MathLang/GenericMathLang/TranslateL4.hs
lib/haskell/natural4/src/LS/XPile/MathLang/MathLang.hs

- Tweak some formatting, like adding line breaks in long code blocks and breaking up long lines into multiple shorter ones.
- Add underscores in front of unused variable names to remove related warnings.
- Eliminate some runtime errors resulting from uses of `error` in the `ToLC` monad stack in favour of `fail` and the `throwError...` functions.
- Prefer string interpolation via `[i|...|]` and `[__i|...|]` forms over manipulating text (resp. strings) via functions from Data.Text (resp. Data.List).
- Abstract some calls to the concrete `ToLC` constructor to the `mkToLC` helper function.
- Introduce the module `LS.XPile.MathLang.GenericMathLang.ArithOps`, which contains hashsets of arithmetic ops, and modify
`isFun` and `isOp` (found in `baseExpifyMTEs`) to use these as lookup tables for …

Cleanup mathlang

---

.github/workflows/haskell.yml
lib/haskell/natural4/stack.yaml
lib/haskell/natural4/stack.yaml.lock

- Update `actions/checkout` and `actions/cache` workflow actions from `v3` to `v4`.
- Bump GitHub macos runner versions from `macos-12` and `macos-11` to `macos-14` and `macos-13` ahead of the `macos-11` removal on `2024-06-28` (see [here](https://github.com/actions/runner-images/issues/9255) and [here](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)).
- Manually install `pcre` from sources on `macos-*` runners, instead of installing from homebrew via `brew install pcre`.
This avoids the following error when compiling `pcre-light` (used by `pcre-heavy`) on M1 based runners:
```
pcre-light          > clang: warning: -Wl,-no_warn_duplicate_libraries: 'linker' input …
```

Update GitHub workflows

---

lib/haskell/explainable/src/Explainable/MathLang.hs

Handle the 'MathPred' constructor in 'eval'.
If the predicate evaluates to true, we report '1', and '0' otherwise.

explainable: Handle 'eval' for MathPred

---

.github/workflows/docker-publish.yml
.github/workflows/haskell.yml
docker/Dockerfile.dsl-ci
lib/haskell/stack.yaml
lib/haskell/stack.yaml.lock

Note that dropping support for the old macos-13 should help to speed up CI tests, as compilation there was really slow due to stack builds not being cached correctly there. This is not an issue on `ubuntu-latest` (currently `ubuntu-22.04) and `macos-latest` (currently `macos-14`).

Update GitHub workflows and bump stack resolver lts

---

lib/haskell/explainable/src/Explainable.hs
lib/haskell/explainable/src/Explainable/MathLang.hs
lib/haskell/natural4/test/LS/XPile/GenericMathLang/TranslateL4Spec.hs

Migrate the explainable pipeline to actually fail on unknown variables.
This improves error messages and avoids relying on implementation
details (e.g., unknown variables default to some value).
Further, move the eval pipeline away from `IO`. Logging should be
happening in a logging monad, and traces shouldn't be part of the
codebase.
This allows us to choose the evaluation monad at run-time.

Refactor explainable MathLang to throw errors for unknown variables

---

lib/haskell/explainable/explainable.cabal
lib/haskell/explainable/package.yaml
lib/haskell/explainable/src/Explainable/MathLang.hs
lib/haskell/explainable/test/LibSpec.hs

The show instance should be used only for debugging. This allows us to analyse the AST when required (e.g., for debugging), but we also need to be able to show human readable text for explanations. Prettified AST nodes are now printed via the `Pretty` type class.

Add Pretty instance for MathLang Expr/Pred

---

docker/Dockerfile.dsl-ci
lib/haskell/stack.yaml
lib/haskell/stack.yaml.lock

- The most notable changes as part of the stack-lts bump are:
- `ghc` has been upgraded from `9.6.5` to `9.6.6`, which fixes some potential compilation bugs.
- `string-interpolate has been updated from `0.3.3.0` to `0.3.4.0`, which may help to improve compilation rimes.
- In addition, this PR also tweaks the dockerfile `docker/Dockerfile.dsl-ci` to use the official Haskell Stack docker images `fpco/stack-build-small` as the base.

bump stack to lts-22.29

---

lib/haskell/natural4/src/LS/XPile/MathLang/GenericMathLang/TranslateL4.hs

In anticipation of adding another :musical_note: transpilation backend (simala), I am aggressively dropping unused code in the code paths that I feel are most relevant for the next steps.
The exported functions have been determined by the minimal set of functions required to compile the rest of the project. Only the exception type got special treatment for now.
If there were any plans for these functions, please speak up and add justifications for why they should be allowed to stay in the codebase :angel:

Enable -Wall for `TranslateL4.hs`

---

lib/haskell/natural4/natural4.cabal
lib/haskell/natural4/package.yaml

I had to add a constraint to build with cabal on my machine (disregarding potential freeze file). I'm not sure if the bound is precise, but it's consistent with the currently used Stackage snapshot, so it should increase accuracy of the dependencies and be harmless.

Add a constraint on graphviz version.

---

docker/Dockerfile.dsl-ci
lib/haskell/explainable/app/Main.hs
lib/haskell/explainable/app/Options.hs
lib/haskell/explainable/app/Schema.hs
lib/haskell/explainable/app/Server.hs
lib/haskell/explainable/explainable.cabal
lib/haskell/explainable/package.yaml
lib/haskell/hie.yaml

Introduce a REST API implemented via servant to expose two endpoints for MathLang. The three endpoints allow to run a function and run a function using pre-defined parameters.
The endpoints are:
* GET  /functions: Get the name and description of all known functions.
* GET  /functions/\<name\>: Get the description and parameters of the given function.
* POST /functions/\<name\>: Run the function with the given parameters.
---
To give some examples on how to run these experiments:
In one terminal, run:
```sh
> stack run explainable-exe
```
In another terminal, you can experiment with:
```sh
> curl -X GET http://localhost:8081/functions | jq
[
{
"function": {
"description": "Determines if a person qualifies for the purposes of the rule. ...",
"name": "compute_qualifies"
},
"type": "function" …
```

Implement servant frontend for explainable MathLang

---

lib/haskell/explainable/app/Schema.hs
lib/haskell/explainable/app/Server.hs

Allows query parameters of functions to be yes/no in addition to true/false.
Additionally, add a parameter schema for the function parameters, making it easier for lagpt to figure out the type of a parameter.

Add support for yes/no in addition to true/false

---

lib/haskell/natural4/app/Main.hs
lib/haskell/natural4/src/LS/XPile/Purescript.hs
lib/haskell/natural4/test/LS/XPile/PurescriptSpec.hs

The PRs #617 and #615 simultaneously changed NLGEnv initialisation code.
The PRs weren't rebased after one of them got merged, leading to inconsistent code.

Fix build errors introduced by PR merges

---

lib/haskell/web-service/package.yaml
lib/haskell/web-service/src/Backend/Api.hs
lib/haskell/web-service/src/Backend/Explainable.hs
lib/haskell/web-service/src/Backend/Simala.hs
lib/haskell/web-service/src/Examples.hs
lib/haskell/web-service/src/Schema.hs
lib/haskell/web-service/src/Server.hs
lib/haskell/web-service/test/SchemaSpec.hs
lib/haskell/web-service/web-service.cabal

Add compatibility with https://docs.oracle.com/en/cloud/saas/b2c-service/opawx/using-batch-assess-rest-api.html

Add support for Oracle Assistant Batch API

---

lib/haskell/cabal.project

It does not seem to be needed.

Remove allow-newer for Cabal and Cabal-syntax

---

lib/haskell/cabal.project

Without this, `cabal repl --enable-multi-repl all` fails.

Allow-newer for baby-l4 to allow the usage of cabal repl --enable-multi-repl
